### ISSUE TITLE
bug(ParameterParser): missing `optional` property

### ISSUE THREAD

**Issue by rishabhmalik759** [RealShadowNova/typedoc-json-parser#102]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

When docs are generated the ClassMethodParser does not have optional flag in properties.

### Steps To Reproduce

Create a class with a method, add optional parameter to the method and generate docs.

### Expected behavior

optional flag should be provided for the the parameter which is generated by typedoc

**Comment by RealShadowNova** [comment]
Thank you for this report! I will be working on this as soon as I can,
