### ISSUE TITLE
bug: Type description null

### ISSUE THREAD

**Issue by Maggi64** [RealShadowNova/typedoc-json-parser#115]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

Thank you for this library!
The description field of a type is null. But it think it shouldn't.

### Steps To Reproduce

Open: https://stackblitz.com/edit/node-albvvu?file=extractedTypes.json

![image](https://user-images.githubusercontent.com/20517052/222773877-c98b4e3a-0b11-4e78-866e-e2d0fba2b66b.png)

### Expected behavior

Should have description like the other types.

**Comment by RealShadowNova** [comment]
Thank you for the issue, could you also provide the code along with the generated json? If you have this in a repository that would be even easier for me to reproduce.

**Comment by RealShadowNova** [comment]
I did not see the sidebar with other files, apologies. I'll take a look when I get a chance.

**Comment by RealShadowNova** [comment]
If a type-alias is a function type, the comments are moved to the appropriate signatures of the function. This is expected behavior for functions in TypeScript. This being the case I'll close this issue as resolved.
