### ISSUE TITLE
request: Add flags to InterfacePropertyParser

### ISSUE THREAD

**Issue by Conner1115** [RealShadowNova/typedoc-json-parser#137]
### Is there an existing issue or pull request for this?

- [X] I have searched the existing issues and pull requests

### Feature description

I'm using this amazing parser tool to render custom docs based on a JSON file generated by typedoc.  So far, the classes have been amazingly useful, but when I was looking for flags on interface properties, I hit a brick wall.

### Desired solution

The feature I'm requesting is to add flags (`isOptional`, etc) to the `InterfacePropertyParser` class so that I can display whether a property is optional or not.

### Alternatives considered

The only alternative is to read and parse the raw typedoc JSON file with JSON.parse, which will most likely turn out disastrous without consistent typing 😰

**Comment by RealShadowNova** [comment]
Instead of `*Parser#flags`, I opted to take the flags that are relevant to the specific parser and make them direct properties.

e.g. `InterfacePropertyParser#optional`

**Comment by Conner1115** [comment]
Thanks for the speedy response!  I did some digging in the code and couldn't find any `optional` property specifically for interface properties.  Does this exist in the latest version?

**Comment by RealShadowNova** [comment]
You know what, you're right. I'm not sure why I decided not to add an `optional` property. For now you should be able to check if `InterfaceTypeParser#type` is an instance of `OptionalTypeParser`.

I'll see what I can do to add this as a feature in the next minor update. Thank you for the report!

**Comment by Conner1115** [comment]
Awesome, thank you!!
