### ISSUE TITLE
bug: Module '"typedoc-json-parser"' has no exported member 'ProjectParser'.

### ISSUE THREAD

**Issue by equinusocio** [RealShadowNova/typedoc-json-parser#179]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

`Module '"typedoc-json-parser"' has no exported member 'ProjectParser'.`

### Steps To Reproduce

Just import `ProjectParser` like the readme says.

### Expected behavior

`ProjectParser` should exist

### Screenshots

![CleanShot 2023-09-25 at 11 54 27](https://github.com/RealShadowNova/typedoc-json-parser/assets/10454741/a9ee1e54-b032-43d5-aaf9-b097bf5ca271)

### Additional context

Imports inside `dist` are completely broken since they start with `#` which is not allowed in non ESM packages/files

![CleanShot 2023-09-25 at 13 07 23](https://github.com/RealShadowNova/typedoc-json-parser/assets/10454741/c75a0a21-5ee2-4a53-8f88-a56929e78c9a)

**Comment by RealShadowNova** [comment]
The [latest release](https://github.com/RealShadowNova/typedoc-json-parser/releases/tag/v9.0.0) has a breaking change stating this package is now ESM only.


v9 of this package has been out for awhile, but I just now realized I never made a GitHub Release for it.

**Comment by equinusocio** [comment]
OK, this wasn't clear since there was no release on github and no documentation.
