### ISSUE TITLE
request: Update to typedoc 0.26

### ISSUE THREAD

**Issue by sndrrth** [RealShadowNova/typedoc-json-parser#250]
### Is there an existing issue or pull request for this?

- [X] I have searched the existing issues and pull requests

### Feature description

Please update typedoc to the latest version (0.25.13 => 0.26.2). We cannot update typedoc in our app because it will show an error "TypeDoc has been loaded multiple times".

### Desired solution

Update to latest version of typedoc.

### Alternatives considered

Adding an npm override works but is ugly.

**Comment by RealShadowNova** [comment]
I will be updating to latest typedoc later today. There were a lot of breaking changes so I need to go through and fix them all.

**Comment by RealShadowNova** [comment]
#249
